version: "3.0"
services:
  dockerapp:
    image: vanchinathan83/dockerapp
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
    depends_on:
      - redis
  redis:
    image: redis:3.2.0
    deploy:
      replicas: 2 
